spring.application.name=follow-me

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

#spring.main.log-startup-info=false

spring.banner.location=classpath:banner.txt