spring.application.name=follow-me

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

#spring.main.log-startup-info=false
logging.level.root=WARN
debug=false

spring.banner.location=classpath:banner.txt

spring.messages.basename=messages
spring.messages.fallback-to-system-locale=false
spring.messages.encoding=UTF-8

spring.config.import=application-actuator.properties