#spring.main.log-startup-info=false

# setting up log levels
logging.level.root=WARN
# change the log level for specific packages
logging.level.com.cyberapple.followme.services=DEBUG
# specific logger for spring data JPA (so it is basically package name)
logging.level.org.springframework.data.jpa.repository.query=TRACE
logging.level.h2.console=DEBUG
debug=false

logging.config=classpath:placeholders/logback-spring.xml

#spring boot dev tools config
spring.output.ansi.enabled=ALWAYS